version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: uvicorn backend.app:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Europe/Paris

  web:
    build:
      context: frontend
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - "5173:80"
